import Head from 'next/head';
import Link from 'next/link';

interface PropTypes {
  products: any;
}

function Home(props: PropTypes) {
  const {products} = props;
  return (
    <div>
      <Head>
        <title>Serverside gendering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2>Server side gendering</h2>
        <ul>
          {products.map((pro: any, index: number) => {
            return (
              <li key={index}>
                <Link href={`/static-path/${pro.Id}`}>{pro.Title}</Link>
              </li>
            )
          })}
        </ul>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://hhq.somee.com/api/News?offSet=0&pageSize=0`);
  const products = (await res.json()).Data.Data;
  return {
    props: {
      products
    },
  }
}

export default Home
