import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface PropTypes {
  products: any;
}

function Home(props: PropTypes) {
  const {products} = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          {products.map((pro: any, index: number) => {
            return (
              <li key={index}>
                {pro.Title}
              </li>
            )
          })}
        </ul>
      </div>
    </div>
  )
}

// export async function getServerSideProps() {
//   const res = await fetch(`https://tano-api.herokuapp.com/products`);
//   const products = await res.json()
//   return {
//     props: {
//       products
//     }
//   }
// }

export async function getStaticProps() {
  const res = await fetch(`https://hhq.somee.com/api/News?offSet=0&pageSize=0`);
  console.log('Abc:', res);
  console.log('________________________________________________', new Date());
  const products = (await res.json()).Data.Data;
  return {
    props: {
      products
    },
  }
}

export default Home
